---

gies:
  n_samples: 1000
  __run__:
    n_cpus: 1
    n_gpus: 0
    hours: 0
    mins: 20


igsp:
  n_samples: 1000
  alpha: 0.001
  ci_test: gaussian
  rank_fail_add: 0.0001
  rank_check_tol: 0.000001
  __run__:
    n_cpus: 1
    n_gpus: 0
    hours: 0
    mins: 20


dcdi:
  reg_coeff: 1.0
  model: DCDI-G
  learning_rate: 0.0001
  num_layers: 1
  hid_dim: 8
  train_batch_size: 64
  num_train_iter: 500000
  use_gpu: false
  __run__:
    n_cpus: 4
    n_gpus: 0
    mem: 4000
    hours: 23
    mins: 59


llc:
  reg_coeff: 10.0
  __run__:
    n_cpus: 1
    n_gpus: 0
    hours: 0
    mins: 20


nodags:
  lambda_c: 0.01
  lr: 0.01
  n_hidden: 3
  n_lip_iter: 10
  __run__:
    n_cpus: 3
    n_gpus: 0
    hours: 0
    mins: 59


ours-linear_u_diag:

  model: linear_u_diag

  bandwidth: 3.0
  reg_strength: 0.1

  # optimization
  batch_size: 512
  batch_size_env: 1
  steps: 20000
  optimizer: adam
  learning_rate: 0.001
  init_scale: 0.001
  init_diag: 0.0
  init_intv_at_mean: true
  grad_clip_val: null
  reg_type: glasso
  learn_intv_scale: false
  auto_diff: true
  sampler_eps: 0.0
  reg_eps: 0.0
  force_linear_diag: true

  # simulation (for prediction only)
  sde:
    method: explicit
    rollout_restarts: 10
    n_samples_burnin: 100
    thinning: 500
    dt: 0.01

  log_every: 200
  log_long_every: 100000000

  __run__:
    n_cpus: 3
    n_gpus: 1
    mem: 4000
    hours: 1
    mins: 59
    gpu_model: rtx_2080_ti


ours-lnl_u_diag:

  model: lnl_u_diag
  mlp_hidden: 8
  mlp_activation: sigmoid
  mlp_init: uniform

  bandwidth: 3.0
  reg_strength: 0.1

  # optimization
  batch_size: 512
  batch_size_env: 1
  steps: 20000
  optimizer: adam
  learning_rate: 0.001
  init_scale: 0.001
  init_diag: 0.0
  init_intv_at_mean: true
  grad_clip_val: null
  reg_type: glasso
  learn_intv_scale: false
  auto_diff: true
  sampler_eps: 0.0
  reg_eps: 0.0
  force_linear_diag: true

  # simulation (for prediction only)
  sde:
    method: explicit
    rollout_restarts: 10
    n_samples_burnin: 100
    thinning: 500
    dt: 0.01

  log_every: 200
  log_long_every: 100000000

  __run__:
    n_cpus: 2
    n_gpus: 1
    mem: 4000
    hours: 2
    mins: 59
    gpu_model: rtx_2080_ti